// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"gopher/entity/activity/activityapi"
	"gopher/entity/activity/activityrepo"
	"gopher/entity/auth/authapi"
	"gopher/entity/city/cityapi"
	"gopher/entity/city/cityrepo"
	"gopher/entity/document/documentapi"
	"gopher/entity/document/documentrepo"
	"gopher/entity/gift/giftapi"
	"gopher/entity/gift/giftrepo"
	"gopher/entity/role/roleapi"
	"gopher/entity/role/rolerepo"
	"gopher/entity/service"
	"gopher/entity/setting/settingapi"
	"gopher/entity/setting/settingrepo"
	"gopher/entity/user/userapi"
	"gopher/entity/user/userrepo"
	"gopher/internal/core"
)

// Injectors from wire.go:

func initSettingAPI(e *core.Engine) settingapi.SettingAPI {
	settingRepo := settingrepo.ProvideSettingRepo(e)
	settingService := service.ProvideSettingService(settingRepo)
	settingAPI := settingapi.ProvideSettingAPI(settingService)
	return settingAPI
}

func initRoleAPI(e *core.Engine) roleapi.RoleAPI {
	roleRepo := rolerepo.ProvideRoleRepo(e)
	roleService := service.ProvideRoleService(roleRepo)
	roleAPI := roleapi.ProvideRoleAPI(roleService)
	return roleAPI
}

func initUserAPI(engine *core.Engine) userapi.UserAPI {
	userRepo := userrepo.ProvideUserRepo(engine)
	userService := service.ProvideUserService(userRepo)
	userAPI := userapi.ProvideUserAPI(userService)
	return userAPI
}

func initAuthAPI(e *core.Engine) authapi.AuthAPI {
	authService := service.ProvideAuthService(e)
	authAPI := authapi.ProvideAuthAPI(authService)
	return authAPI
}

func initActivityAPI(engine *core.Engine) activityapi.ActivityAPI {
	activityRepo := activityrepo.ProvideActivityRepo(engine)
	activityService := service.ProvideActivityService(activityRepo)
	activityAPI := activityapi.ProvideActivityAPI(activityService)
	return activityAPI
}

func initDocumentAPI(engine *core.Engine) documentapi.DocumentAPI {
	documentRepo := documentrepo.ProvideDocumentRepo(engine)
	documentService := service.ProvideDocumentService(documentRepo)
	documentAPI := documentapi.ProvideDocumentAPI(documentService)
	return documentAPI
}

func initCityAPI(engine *core.Engine, documentService service.DocumentService) cityapi.CityAPI {
	cityRepo := cityrepo.ProvideCityRepo(engine)
	cityService := service.ProvideCityService(cityRepo, documentService)
	cityAPI := cityapi.ProvideCityAPI(cityService)
	return cityAPI
}

func initGiftAPI(engine *core.Engine, documentService service.DocumentService) giftapi.GiftAPI {
	giftRepo := giftrepo.ProvideGiftRepo(engine)
	giftService := service.ProvideGiftService(giftRepo, documentService)
	giftAPI := giftapi.ProvideGiftAPI(giftService)
	return giftAPI
}
