package terms

// term
const (
	Created       = "created"
	Updated       = "updated"
	Deleted       = "deleted"
	Saved         = "saved"
	List          = "list"
	Info          = "info"
	Language      = "language"
	Profile       = "profile"
	Auth          = "auth"
	ResetPassword = "reset-password"

	// entities
	Role       = "role"
	Roles      = "roles"
	Resources  = "resources"
	User       = "user"
	Users      = "users"
	Setting    = "setting"
	Settings   = "settings"
	Activity   = "activity"
	Activities = "activities"
	Document   = "document"
	Documents  = "documents"
	City       = "city"
	Cities     = "cities"
	Gift       = "gift"
	Gifts      = "gifts"

	// messages
	VInfo                    = "%v info"
	ListOfV                  = "list of %v"
	AllV                     = "all %v"
	VCreatedSuccessfully     = "%v created successfully"
	VUpdatedSuccessfully     = "%v updated successfully"
	VDeletedSuccessfully     = "%v deleted successfully"
	UserLoggedInSuccessfully = "user logged in successfully"

	// error messages
	InternalServerError                    = "internal server error"
	RouteNotFound                          = "route not found"
	Unauthorized                           = "unauthorized"
	RecordNotFound                         = "record not found"
	RecordNotFoundForInVTable              = "record not found in %v table"
	VisNotValid                            = "%v is not valid"
	BindFailed                             = "bind failed"
	ValidationFailed                       = "validation failed"
	ValidationForVFailedInV                = "validation for %v failed in %v"
	BadRequest                             = "bad request"
	BadRequestForVInV                      = "bad request for %v in %v"
	VisRequired                            = "%v is required"
	MinimumAcceptedCharacterForVisV        = "minimum accepted character for %v is %v"
	MaximumAcceptedCharacterForVisV        = "maximum accepted character for %v is %v"
	MinimumAcceptedValueForVisV            = "minimum accepted value for %v is %v"
	MaximumAcceptedValueForVisV            = "maximum accepted value for %v is %v"
	AcceptedValueForVareV                  = "accepted values for %v are: %v"
	DuplicateHappened                      = "duplicate happened"
	ForeignKeyError                        = "foreign key error"
	VisAlreadyExistInTableV                = "%v is already exist in table %v"
	VisUniqueInTableV                      = "%v is unique in table %v"
	ItHasRelationWithSomeElementSoItIsNotV = "it has relation with some element, so it is not %v"
	ErrorInBindingV                        = "error in binding %v"
	ErrorInBinding                         = "error in binding"
	InvalidV                               = "invalid %v "
	InvalidValueDoNotIncloudV              = "invalid value didn't include %v "
	TokenIsRequired                        = "token is required"
	TokenIsNotValid                        = "token is not valid"
	TokenIsExpired                         = "token is expired"
	CanNotInGenerateToken                  = "can't in generate token"
	CheckThisVField                        = "check this %v fields"
	Forbidden                              = "forbidden"
	UsernameOrPasswordIsWrong              = "username or password is wrong"
	SomethingWentWrong                     = "something went wrong"
	YouDoNotHavePermission                 = "you don't have permission"
	CanNotGenerateTheExcelList             = "can't generate the excel list"
	OldPasswordIsWrong                     = "old password is wrong"
	ResetPasswordSuccessfully              = "reset password successfully"
	RequestToResetPasswordSuccessfull      = "request to reset password successful"
	UserDataInvalidTryToSendRequestAgain   = "user data invalid try to send request again"
	ProvidedEmailIsWrong                   = "provided email is wrong"
	DocumentTypeIsWrong                    = "document type is wrong"
	CouldNotDeleteDocuments                = "couldn't delete documents"
	DocumentTypeNotAccepted                = "document type not accepted"
	CouldNotUploadDocument                 = "couldn't upload document"
	CanNotUploadMultipleDocument           = "can't upload multiple document"
	DocumentDidNotSaved                    = "document didn't saved"
	HashingPasswordFailed                  = "hashing password failed"
)
